name: VPC Service Controls Request
description: Request to add one or more ingress/egress rules to VPC Service Controls perimeters
labels: [vpc-sc-request]

body:
  - type: input
    id: reqid
    attributes:
      label: Request ID
      placeholder: e.g. REQ-1234567
    validations:
      required: true

  - type: dropdown
    id: perimeters
    attributes:
      label: Perimeter Name(s)
      multiple: true
      options:
        - test-perim-a
        - test-perim-b
    validations:
      required: true

  - type: dropdown
    id: direction
    attributes:
      label: Direction
      options:
        - EGRESS
        - INGRESS
    validations:
      required: true

  - type: textarea
    id: services
    attributes:
      label: Services
      description: Enter one or more service names (comma-separated), e.g. `bigquery.googleapis.com, storage.googleapis.com`
    validations:
      required: true

  - type: textarea
    id: methods
    attributes:
      label: Methods (optional)
      description: |
        Provide methods using `service: method1,method2; service2: method`.
        Omit to allow all methods for a service.
    validations:
      required: false

  - type: textarea
    id: permissions
    attributes:
      label: Permissions (optional)
      description: |
        Provide permissions using `service: perm1,perm2; service2: perm`.
        Omit to allow none.
    validations:
      required: false

  - type: textarea
    id: identities
    attributes:
      label: Identities
      description: |
        Enter principals separated by commas (e.g. `serviceAccount:sa@project.iam.gserviceaccount.com, group:team@company.com`)
    validations:
      required: true

  - type: textarea
    id: sources
    attributes:
      label: Source / From
      description: |
        For INGRESS rules, list source projects/resources or CIDR ranges (e.g. `projects/9876543210, 10.1.2.0/24`).
        Leave blank for EGRESS.
    validations:
      required: false

  - type: textarea
    id: destinations
    attributes:
      label: Destination / To
      description: |
        For EGRESS rules, list destination projects/resources (e.g. `projects/1234567890`).
        Leave blank for INGRESS.
    validations:
      required: false

  - type: input
    id: tlm_id
    attributes:
      label: TLM‑ID (if applicable)
      placeholder: e.g. TLM-123456
    validations:
      required: false

  - type: textarea
    id: justification
    attributes:
      label: Justification
      description: Provide a short justification for the request.
    validations:
      required: true