name: 🔒 VPC Service Controls Access Request
description: Fix VPC SC access errors quickly
title: "[VPC SC] "
labels: [vpc-sc-request]

body:
  - type: markdown
    attributes:
      value: |
        ## Quick VPC SC Access Request

        **Got a VPC SC error?** Paste it below and we'll handle the rest!

        Most fields are optional - we auto-detect from your error message.

        ---

  - type: input
    id: reqid
    attributes:
      label: Request/Ticket ID
      placeholder: REQ1234567
    validations:
      required: true

  - type: textarea
    id: error_message
    attributes:
      label: ⭐ ERROR MESSAGE - Paste your full error here
      description: |
        **PASTE YOUR FULL VPC SC ERROR MESSAGE**
        We auto-extract: perimeter names, services, project numbers, and more!
      placeholder: |
        Paste the full error from Cloud Console, logs, or your terminal.

        Example:
        Request is prohibited by organization's policy.
        vpcServiceControlsUniqueIdentifier: yBL4S...
        serviceName: "bigquery.googleapis.com"
        resourceName: "projects/987654321/datasets/my_dataset"
        perimeterName: "accessPolicies/123/servicePerimeters/prod-data-perimeter"
    validations:
      required: false

  - type: textarea
    id: what_trying_to_do
    attributes:
      label: What are you trying to do?
      description: Describe in plain English (helps if error message is incomplete)
      placeholder: |
        Example: "Reading BigQuery data from prod project in my dev Cloud Run service"
    validations:
      required: true

  - type: input
    id: source_identity
    attributes:
      label: Service Account
      description: What service account is making the request?
      placeholder: my-service@my-project.iam.gserviceaccount.com
    validations:
      required: true

  - type: input
    id: source_project
    attributes:
      label: Source Project Number (optional if in error)
      description: Where is the request coming FROM?
      placeholder: "1234567890"
    validations:
      required: false

  - type: input
    id: dest_project
    attributes:
      label: Destination Project Number (optional if in error)
      description: What project are you trying to ACCESS?
      placeholder: "9876543210"
    validations:
      required: false

  - type: dropdown
    id: service
    attributes:
      label: GCP Service (optional if in error)
      options:
        - (Will auto-detect from error)
        - bigquery.googleapis.com
        - storage.googleapis.com
        - pubsub.googleapis.com
        - run.googleapis.com
        - artifactregistry.googleapis.com
        - compute.googleapis.com
        - logging.googleapis.com
        - iam.googleapis.com
        - Other
    validations:
      required: false

  - type: input
    id: external_ip
    attributes:
      label: External IP (only if accessing from outside GCP)
      placeholder: "203.0.113.50/32"
    validations:
      required: false

  - type: dropdown
    id: source_perimeter
    attributes:
      label: Source Perimeter (optional - we auto-detect)
      description: Only fill if you know it and it's NOT in the error
      options:
        - (Auto-detect from error or cache)
        - test-perim-a
        - test-perim-b
    validations:
      required: false

  - type: dropdown
    id: dest_perimeter
    attributes:
      label: Destination Perimeter (optional - we auto-detect)
      description: Only fill if you know it and it's NOT in the error
      options:
        - (Auto-detect from error or cache)
        - test-perim-a
        - test-perim-b
    validations:
      required: false

  - type: textarea
    id: justification
    attributes:
      label: Business Justification
      description: Why do you need this access?
      placeholder: Our ETL pipeline needs this data for daily reports...
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      options:
        - Normal (24-48 hours)
        - Urgent (4 hours)
        - Critical (production down)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---

        ## What Happens Next?

        1. 🤖 We auto-extract perimeters, services, projects from your error
        2. ✅ Create the right INGRESS/EGRESS rules automatically
        3. 📋 PRs created to the correct perimeter repos
        4. 👀 NetSec reviews (usually < 24 hours)
        5. 🚀 Auto-deploys when approved

        **Questions?** Comment on this issue after submitting.
