name: VPC Service Controls Request

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  process_vpc_sc_request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Write issue body to file
        run: echo "${{ github.event.issue.body }}" > issue_body.md

      - name: Install dependencies
        run: python -m pip install --quiet pyyaml

      - name: Configure git for cross‑repo pushes
        run: |
          git config --global url."https://x-access-token:${{ secrets.CROSS_REPO_TOKEN }}@github.com/".insteadOf https://github.com/

      - name: Run VPC SC request handler
        run: |
          python3 .github/scripts/vpc_sc_request_handler.py \
            --issue-file issue_body.md \
            --router-file router.yml \
            --workdir . \
            --output request_processing.json

      - name: Read actions from summary
        id: read_actions
        run: |
          if [ -f request_processing.json ]; then
            python3 -c "import json; print(json.load(open('request_processing.json')).get('actions', []))"
          else
            echo "[]"
          fi

      - name: Apply changes and create PRs
        if: steps.read_actions.outputs.stdout != '[]'
        env:
          CROSS_REPO_TOKEN: ${{ secrets.CROSS_REPO_TOKEN }}
          GH_TOKEN: ${{ secrets.CROSS_REPO_TOKEN }}
        run: |
          if [ ! -f request_processing.json ]; then
            echo "request_processing.json not found; skipping PR creation."
            exit 0
          fi
          python3 - <<'PY'
          import json, os, re, subprocess

          def extract_array_body(new_content, array_name):
              marker = f"{array_name} = ["
              idx = new_content.find(marker)
              if idx == -1:
                  return ""
              idx = new_content.find("[", idx) + 1
              depth = 1
              i = idx
              while depth > 0 and i < len(new_content):
                  if new_content[i] == "[":
                      depth += 1
                  elif new_content[i] == "]":
                      depth -= 1
                  i += 1
              return new_content[idx:i-1].strip()

          def update_array(existing, array_name, new_body):
              pattern = re.compile(rf"^{array_name}\\s*=\\s*\\[.*?\\]", re.MULTILINE | re.DOTALL)
              if pattern.search(existing):
                  return pattern.sub(f"{array_name} = [\n{new_body}\n]", existing)
              else:
                  return existing + f"\n{array_name} = [\n{new_body}\n]\n"

          data = json.load(open('request_processing.json'))
          for action in data.get('actions', []):
              repo     = action['repo']
              branch   = action['branch']
              commit   = action['commit_message']
              pr_title = action['pr_title']
              pr_body  = action['pr_body']
              changes  = action['changes']
              repo_dir = f"tmp/{repo.replace('/', '_')}"
              subprocess.run(['git', 'clone', f'https://github.com/{repo}.git', repo_dir], check=True)
              subprocess.run(['git', '-C', repo_dir, 'checkout', '-b', branch], check=True)

              for change in changes:
                  file_path = os.path.join(repo_dir, change['file'])
                  new_content = change['content']
                  ingress_body = extract_array_body(new_content, 'ingress_policies')
                  egress_body  = extract_array_body(new_content, 'egress_policies')
                  existing = ""
                  if os.path.exists(file_path):
                      with open(file_path) as f:
                          existing = f.read()
                  updated = existing
                  if ingress_body:
                      updated = update_array(updated, 'ingress_policies', ingress_body)
                  if egress_body:
                      updated = update_array(updated, 'egress_policies', egress_body)
                  os.makedirs(os.path.dirname(file_path), exist_ok=True)
                  with open(file_path, 'w') as f:
                      f.write(updated)

              subprocess.run(['git', '-C', repo_dir, 'config', 'user.email', 'bot@example.com'], check=True)
              subprocess.run(['git', '-C', repo_dir, 'config', 'user.name', 'VPC SC Bot'], check=True)
              subprocess.run(['git', '-C', repo_dir, 'add', '.'], check=True)
              status = subprocess.run(['git', '-C', repo_dir, 'status', '--porcelain'], capture_output=True, text=True)
              if status.stdout.strip():
                  subprocess.run(['git', '-C', repo_dir, 'commit', '-m', commit], check=True)
                  subprocess.run(['git', '-C', repo_dir, 'push', '--set-upstream', 'origin', branch], check=True)
                  subprocess.run(['gh', 'pr', 'create', '--repo', repo, '--head', branch,
                                  '--title', pr_title, '--body', pr_body], cwd=repo_dir, check=True)
              else:
                  print(f"No changes to commit for {repo}; skipping PR.")
          PY

      - name: Comment on the issue with summary
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ -f request_processing.json ]; then
            gh issue comment ${{ github.event.issue.number }} --body "$(printf '**VPC Service Controls request processed.**\n```json\n%s\n```' "$(cat request_processing.json)")"
          else
            gh issue comment ${{ github.event.issue.number }} --body "Error: request_processing.json was not generated."
