name: VPC Service Controls Request

on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  process_vpc_sc_request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Write issue body to file
        run: echo "${{ github.event.issue.body }}" > issue_body.md

      - name: Install Python dependencies
        run: python -m pip install --quiet pyyaml

      - name: Configure git for cross-repo pushes
        run: |
          git config --global url."https://x-access-token:${{ secrets.CROSS_REPO_TOKEN }}@github.com/".insteadOf https://github.com/

      - name: Run VPC SC request handler
        run: |
          python3 .github/scripts/vpc_sc_request_handler.py \
            --issue-file issue_body.md \
            --router-file router.yml \
            --workdir . \
            --output request_processing.json

      - name: Validate VPC SC request
        id: validate
        run: |
          python3 .github/scripts/validate_vpc_sc_request.py \
            --issue-file issue_body.md \
            --router-file router.yml

      - name: Read actions from summary
        id: read_actions
        run: |
          python3 -c "import json, os, sys; data=json.load(open('request_processing.json')) if os.path.exists('request_processing.json') else {}; print(json.dumps(data.get('actions', [])))"

      - name: Label and comment if invalid
        if: ${{ steps.validate.outputs.valid != 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ERRORS: ${{ steps.validate.outputs.errors }}
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-label "needs fix"
          python3 -c "import json, os; errs=json.loads(os.environ.get('ERRORS','[]')); body='**Validation Issues Detected:**\\n' + '\\n'.join('- '+e for e in errs); open('comment.md','w').write(body)"
          gh issue comment ${{ github.event.issue.number }} --body "$(cat comment.md)"

      - name: Apply changes and create PRs
        if: ${{ steps.validate.outputs.valid == 'true' && steps.read_actions.outputs.stdout != '[]' }}
        env:
          CROSS_REPO_TOKEN: ${{ secrets.CROSS_REPO_TOKEN }}
          GH_TOKEN: ${{ secrets.CROSS_REPO_TOKEN }}
        run: |
          python3 .github/scripts/apply_changes.py --summary request_processing.json

      - name: Comment with summary
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ -f request_processing.json ]; then
            gh issue comment ${{ github.event.issue.number }} --body "$(printf '**VPC Service Controls request processed.**\\n```json\\n%s\\n```' "$(cat request_processing.json)")"
          else
            gh issue comment ${{ github.event.issue.number }} --body "Error: request_processing.json was not generated."
          fi
